### ISSUE TITLE
编译导入密钥

### ISSUE THREAD

**Issue by Cologler** [arition/DoujinManager-wpf#10]
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2884,5): error MSB3325: 无法导入以下密钥文件: Resources\dmwpfkey.pfx。该密钥文件可能受密码保护。

为啥要加密钥？

**Comment by Cologler** [comment]
又及：release 里面下载的 7z 被报病毒了

**Comment by arition** [comment]
秘钥的话，这是应用签名秘钥。你只要在项目属性里去掉秘钥或者换成自己的秘钥就可以了。
released里的是非常旧的版本，不建议使用。这个项目也很久没有更新了。soulplus那方面的功能现在是瘫痪的，只有ehentai那方面的功能可以用。

**Comment by arition** [comment]
close #10
